wheel = [0, 0]
logo = [0, 1]

# Left stripe
l0 = [0, 2]
l1 = [0, 3]
l2 = [0, 4]
l3 = [0, 5]
l4 = [0, 6]
l5 = [0, 7]
l6 = [0, 8]
l7 = [0, 9]
l8 = [0, 10]

# Right stripe
r0 = [0, 11]
r1 = [0, 12]
r2 = [0, 13]
r3 = [0, 14]
r4 = [0, 15]
r5 = [0, 16]
r6 = [0, 17]
r7 = [0, 18]
r8 = [0, 19]