logo = [0, 20]
esc = [0, 1]
f1 = [0, 3]
f2 = [0, 4]
f3 = [0, 5]
f4 = [0, 6]
f5 = [0, 7]
f6 = [0, 8]
f7 = [0, 9]
f8 = [0, 10]
f9 = [0, 11]
f10 = [0, 12]
f11 = [0, 13]
f12 = [0, 14]
print = [0, 15]
roll = [0, 16]
pause = [0, 17]
m1 = [1, 0]
roof = [1, 1]
1 = [1, 2]
2 = [1, 3]
3 = [1, 4]
4 = [1, 5]
5 = [1, 6]
6 = [1, 7]
7 = [1, 8]
8 = [1, 9]
9 = [1, 10]
0 = [1, 11]
ß = [1, 12]
apostroph = [1, 13]
backspace = [1, 14]
insert = [1, 15]
pos1 = [1, 16]
pgup = [1, 17]
num = [1, 18]
div = [1, 19]
mult = [1, 20]
min = [1, 21]
m2 = [2, 0]
tab = [2, 1]
q = [2, 2]
w = [2, 3]
e = [2, 4]
r = [2, 5]
t = [2, 6]
z = [2, 7]
u = [2, 8]
i = [2, 9]
o = [2, 10]
p = [2, 11]
ü = [2, 12]
+ = [2, 13]
del = [2, 15]
end = [2, 16]
pgdown = [2, 17]
n7 = [2, 18]
n8 = [2, 19]
n9 = [2, 20]
plus = [2, 21]
m3 = [3, 0]
caps = [3, 1]
a = [3, 2]
s = [3, 3]
d = [3, 4]
f = [3, 5]
g = [3, 6]
h = [3, 7]
j = [3, 8]
k = [3, 9]
l = [3, 10]
ö = [3, 11]
ä = [3, 12]
hash = [3, 13]
ret = [3, 14]
n4 = [3, 18]
n5 = [3, 19]
n6 = [3, 20]
m4 = [4, 0]
lshift = [4, 1]
lower = [4, 2]
y = [4, 3]
x = [4, 4]
c = [4, 5]
v = [4, 6]
b = [4, 7]
n = [4, 8]
m = [4, 9]
comma = [4, 10]
dot = [4, 11]
dash = [4, 12]
rshift = [4, 14]
up = [4, 16]
n1 = [4, 18]
n2 = [4, 19]
n3 = [4, 20]
nreturn = [4, 21]
m5 = [5, 0]
lctrl = [5, 1]
super = [5, 2]
alt = [5, 3]
altgr = [5, 11]
menu = [5, 13]
rctrl = [5, 14]
left = [5, 15]
down = [5, 16]
right = [5, 17]
n0 = [5, 19]
ndel = [5, 20]