[mouse]
name = "Razer Mamba Elite"
lightmap = "mamba_elite"

[mouse.lights]
wheel = "cyan"
logo = "white"
l0 = "#ff0"
l1 = "#ffff22"
l7 = "#ffffdd"
l8 = "white"
r0 = "#f0f"
r1 = "#ff22ff"
r7 = "#ffddff"
r8 = "white"

[keyboard]
name = "Razer BlackWidow Chroma"
lightmap = "blackwidow_chroma_de"

[keyboard.lights]
logo = "#dc143c"
w = "coral"
a = "bisque"
s = "lightgreen"
d = "cornflowerblue"